# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foralg <- function(n, N, foo, gamma, allprobs) {
    .Call(`_hornsharkHMM_foralg`, n, N, foo, gamma, allprobs)
}

timesTwo <- function(x) {
    .Call(`_hornsharkHMM_timesTwo`, x)
}

