# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_mc <- function(x, mean, sigma, logd = FALSE, cores = 1L) {
    .Call(`_hornsharkHMM_dmvnrm_arma_mc`, x, mean, sigma, logd, cores)
}

foralg <- function(n, N, foo, gamma, allprobs) {
    .Call(`_hornsharkHMM_foralg`, n, N, foo, gamma, allprobs)
}

timesTwo <- function(x) {
    .Call(`_hornsharkHMM_timesTwo`, x)
}

